### ISSUE TITLE
Downloading a FTB modpack crashes the launcher

### ISSUE THREAD

**Issue by 488Ques** [fn2006/PollyMC#13]
### Operating System

Windows

### Version of PollyMC

PollyMC 1.4.1 Windows x86_64 Portable

### Description of bug

Downloading any FTB modpack appears to resolve the request for a while then crashes the launcher without any log.

I'm not sure whether this is an upstream bug or PollyMC's. I'll close this one if this is PolyMC's.

### Steps to reproduce

1. Open PollyMC
2. Click Add Instance
3. Click FTB
4. Choose any modpack
5. Launcher crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
This is interesting, I can reproduce this but only on Windows, it doesn't happen in the upstream PolyMC build either.
I'll take a look at the code for the new FTB downloader and figure out what's happening.

**Comment by fn2006** [comment]
Alright I figured it out, it seems like FTB packs are hosted on CurseForge servers for some reason, it's crashing because you don't have a CurseForge Core API key set.
The reason I could only reproduce the issue on Windows is because my personal Linux install is set to use the key ripped from Overwolf while my Windows install doesn't have the key set to anything.

I would tell you to use the CurseForge workaround that I link to in the readme but you're on Windows and it uses a bash script to rip the key.
I don't think I'm allowed to rewrite the bash script in powershell either because it doesn't have a licence which means all rights are reserved, so your options are either run the script through WSL2 or read the bash script and execute Windows equivalent commands by hand.

**Comment by 488Ques** [comment]
For anyone else on Windows, the script rips the key from an archived 4chan thread. It's `$2a$10$bL4bIL5pUWqfcO7KQtnMReakwtfHbNKh6v1uTpKlzhwoueEJQnPnm` (Not sure if I should show it here)

The other option is to navigate to [Overwolf website](https://curseforge.overwolf.com), install it. Then navigate to resources/app/dist/desktop/desktop.js and search for cfCoreApiKey. Not sure if this works.

**Comment by fn2006** [comment]
Sorry, I censored your comment because I want to minimize the chances that this repo gets DMCA'd.
But yeah if any other Windows users want the key then go to the 4chan thread that the script rips the key from and CTRL+F `and put`, the first result will be the key.
