### ISSUE TITLE
RFC: Rebase off of PlaceholderMC/PrismLauncher.

### ISSUE THREAD

**Issue by yum13241** [fn2006/PollyMC#29]
### Goal

Get off of the old and dead PolyMC code (it got hacked), and switch to smth actively developed like PrismLauncher.

Github: https://github.com/PlaceholderMC/PrismLauncher

### Motivation

Motivation? The PolyMC code right now is controlled by a rogue dev. Continuing to use it would result in malware. We want a safe launcher, and PrismLauncher is a continuation of PolyMC which is made by all the devs except the rogue one.

### Specification

Rebase PollyMC so it uses PrismLauncher code instead.

### Drawbacks

Potentially having to redo all the DRM removal.

### Unresolved Questions

What will it be called now? How would the dev avoid restarting everything? 

### Alternatives Considered

Rebasing off of MultiMC would be pointless but possible since UltimMC does that.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The name IMO should be changed to further disassociate with PolyMC.

I know this might take a lot of work but I think it's worth it. Changing the meta server doesn't change the fact that a rogue dev now COMPLETELY controls PolyMC.

**Comment by fn2006** [comment]
I was initially planning on waiting a bit in case the Prism team got the PolyMC repo back from Lenny but that seems unlikely at this point and PolyMC's name has already been dragged through the mud so I'll do this pretty soon.

I just don't really want to ditch the PollyMC name, I think it's funny and I'm fond of the parrot icon.
Also you're overestimating the amount of work this will take, if I don't rebrand then literally all I have to do is change the upstream repo that I'm pulling from, since it's the same codebase all of my tweaks and additions will still work.

**Comment by fn2006** [comment]
I'll have a think about the name, also you mentioned that you think the parrot icon is weird, you do realise it's a long winded pun, right?
Since Polly is a common name for parrots and pirates often have parrots.

**Comment by yum13241** [comment]
Oh lol. But out of context it is weird.

If CuboidMC doesn't work for you how about hmmm...


TetraMC, or maybe even PrideMC? (you know since Lenny is anti-queer)

**Comment by yum13241** [comment]
The problem with not changing it is that the words "Polly" and "Poly" are pronounced in the exact same way.

**Comment by GrumpyGammon** [comment]
![ywnbaw](https://user-images.githubusercontent.com/67706588/196675054-9dd58eff-1442-4ff0-9e39-4b774e3bae7b.JPG)

**Comment by fn2006** [comment]
Please keep discussion civil and on-topic, I just had to delete a hateful comment.

**Comment by yum13241** [comment]
> PollyMC name


Ahh well.

**Comment by Fatih120** [comment]
PollyMC is cute. Thanks for your hard work.

**Comment by Azarattum** [comment]
Maybe `Polly Launcher` to both keep the parrot branding and signify the transition to the new upstream?

**Comment by yum13241** [comment]
Yeah that's a good idea. Why didn't I think of that?

**Comment by yum13241** [comment]
> My opinion: It's just safer to rebase off of Prism, 
I 1000% agree.


> because, now that Poly is in the hands of a single, rogue dev, who knows what he might put in?
I'll be blunt. Probably malware. He might be making it as we speak or he might be packaging [Petya.] or some other crap. (https://www.malwarebytes.com/blog/news/2017/07/keeping-up-with-the-petyas-demystifying-the-malware-family)


> And even if you audit the commits coming from Poly, you might miss a thing or two (we're all humans) or it might not look unsafe at first but cause problems later.


I agree with this too. It's simply not worth it to keep using Poly's source.

**Comment by Den4enko** [comment]
Maybe "PollyLauncher"?

**Comment by offbeat-stuff** [comment]
prism launcher 5.0 is launched so pollymc 5.0 when?

**Comment by yum13241** [comment]
Be patient.

**Comment by uriesk** [comment]
PolyMc did not get hacked.
Stop spreading FUD.
And the only difference between Prism and PolyMc is that Prims includes a CODE_OF_CONDUCT.
That is it. There is not more. That is everything this drama is about. The PolyMc maintainer is still the same guy as it always was.

**Comment by TechPro424** [comment]
> PolyMc did not get hacked. Stop spreading FUD. And the only difference between Prism and PolyMc is that Prims includes a CODE_OF_CONDUCT. That is it. There is not more. That is everything this drama is about. The PolyMc maintainer is still the same guy as it always was.

It's not a question of it being hacked now, but a question of being hacked in the future. Now that PolyMC is in the hands of a single person, rather than a group of people, that one person could add whatever code he wants to the launcher and no one can do anything about it. And if we don't notice any malware that was added that way, it could be a disaster, to say the least.

**Comment by fn2006** [comment]
I've seen enough, PollyMC will become a fork of Prism Launcher, it will keep the PollyMC name and icon.

> prism launcher 5.0 is launched so pollymc 5.0 when?

Soon, when Prism 5.1 releases.

> PolyMc did not get hacked.
Stop spreading FUD.

There was a lot of misinformation flying around when this issue was created, I doubt OP was intentionally lying, he was probably just misinformed.

> And the only difference between Prism and PolyMc is that Prims includes a CODE_OF_CONDUCT.
That is it. There is not more. That is everything this drama is about. 

That's not true, over the past week Prism has picked up where PolyMC's development left off, adding ARM support and modpack updating to name a few big changes.
PolyMC on the other hand has had no commits since the creation of this issue and none of the new PRs look very promising to me.

> The PolyMc maintainer is still the same guy as it always was.

While this is technically true, Lenny was never the one developing PolyMC, the people who were developing Poly are now developing Prism, it's Lenny's new team that needs to prove themselves, not Prism's team.

**Comment by uriesk** [comment]
> It's not a question of it being hacked now, but a question of being hacked in the future. Now that PolyMC is in the hands of a single person, rather than a group of people, that one person could add whatever code he wants to the launcher and no one can do anything about it. And if we don't notice any malware that was added that way, it could be a disaster, to say the least.

The creator of this issue says it got hacked.
PolyMC is not in the hands of just one single person. The people who got mad at a CODE_OF_CONDUCT being removed and some Discord drama left and forked. That is it.
What makes you think that the guy who maintained PolyMc for all this time will somehow now add maleware to it, but Prism won't?
Why do you think that those overly political people, who got mad at a CoC removal and who did not maintain such a project before, are somehow more trustworthy?



> I doubt OP was intentionally lying

I think he was. Because he is still around in this issue and never corrected it. If i would make such a mistake unintentionally, i surely would correct it.

**Comment by fn2006** [comment]
> That isn't even true. The people who left to Prism, joined PolyMc after it already got popular. The ones who built it up are still at Poly. 

Just looking at Poly's commits shows that the people who left for Prism were the ones adding new features to PolyMC, without them Poly would just be a rebranded MultiMC.

I can't be bothered to argue with the rest of your points but I will agree that a lot of the people against Poly don't seem to be afraid of lying if it means getting their way.

**Comment by uriesk** [comment]
Do you trust the people who spread lies and who claim that something got "hacked" or "will add malware" (both of those claims right here in this issue) and who go on a witch hunt?
Or do you trust the maintainers who were in charge since its creation?
What makes you think that they will not come for you?

**Comment by fn2006** [comment]
I don't particularly trust either side but I trust Lenny less because he's the one who started this and he's not got much left to lose.

**Comment by fn2006** [comment]
Exactly, if anyone disagrees with my decision to use Prism as the upstream then they can just fork this repo and continue using PolyMC as the upstream.

**Comment by fn2006** [comment]
PollyMC 5.1 is out and based on Prism Launcher.

**Comment by binex-dsk** [comment]
> Get off of the old and dead PolyMC code (it got hacked)

It wasn't.

**Comment by offbeat-stuff** [comment]
Well its certainly old as the new prism launcher is getting a whole lot of features.
What is polymc doing.

Hi, @binex-dsk I know you are a troll, but hey lets have some fun.

**Comment by binex-dsk** [comment]
I've only made one troll thread on this website, this isn't a troll. PolyMC was never compromised and is far more stable than Prism (which has yet to properly work for me).

**Comment by yum13241** [comment]
> PolyMC was never compromised and is far more stable than Prism (which has yet to properly work for me).

You gotta be trolling.

**Comment by binex-dsk** [comment]
> > PolyMC was never compromised and is far more stable than Prism (which has yet to properly work for me).
> 
> You gotta be trolling.

I'm not. PolyMC was never compromised.

**Comment by yum13241** [comment]
> I'm not. PolyMC was never compromised.

Then why did one developer kick everyone from the project?

**Comment by binex-dsk** [comment]
All of this has been explained dozens of times before. The fact that you need to ask me this question shows me that your entire idea of PolyMC being "compromised" came from media sites that made it seem like people using PolyMC were immediately going to get their computers hacked with malware, from the dangerous Lenny man. That's not legal or even possible to do with the launcher code at the time of the incident. Said media outlets refused to further comment when Lenny sent a signed PGP message confirming that it was really him.

I'm not explaining this again. If you want to understand the situation fully instead of spitting out meaningless insults, one-liner loaded questions that have been answered 100 times before, and fearmongering about a Minecraft launcher run by a random guy you'll never meet, read [this](https://github.com/flathub/flathub/issues/3600) issue. Takes about 15-20 minutes. Also contains a healthy amount of hilariously Twitter-esque banter to keep you entertained, I read this a few days ago and laughed quite a bit.

Regardless, considering this project is over a year into using the Prism base, and biased, one-sided news outlets have done enough fearmongering to convince people that PolyMC is the worst thing since Windows 9x mailbombs and macro viruses, this entire discussion is meaningless banter with no purpose. Also, if you really want to dissociate with PolyMC I would highly recommend changing the name because I've already had a few of my friends get confused.
