### ISSUE TITLE
Cannot add a microsoft account

### ISSUE THREAD

**Issue by Alessandro5558** [fn2006/PollyMC#48]
### Operating System

Windows 11 Pro 22H2

### Version of PollyMC

PollyMC 6.1

### Version of Qt

Qt 6.4.1

### Description of bug

There is no button to add a Microsoft account

### Steps to reproduce

Open pollyMC
Go to the account section
The Add a Microsoft account button is grayed out

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
See https://github.com/fn2006/PollyMC/issues/16, if you want to use a Microsoft account just use Prism Launcher.

**Comment by DraconicNEO** [comment]
> See #16, if you want to use a Microsoft account just use Prism Launcher.

Would be nice if there was a way due to how Prism Removes the desirable features like FTB and Curseforge support, not everyone who uses this or wants to use this does it for "Piracy" and if they want to play on servers (especially ones that use modpacks) it would be more convenient to be able to login to MSA since most servers don't use ely.by's auth system (how can they the Docs are terrible and in russian).
