### ISSUE TITLE
[Question] Which Windows build do I use?

### ISSUE THREAD

**Issue by yum13241** [fn2006/PollyMC#50]
Do I use the MSVC version or the MinGW version? Why do you have both anyway? I'm not a turbonerd. Sorry for disturbing you.

**Comment by fn2006** [comment]
Honestly I'm not too sure but the download link for Windows on the Prism Launcher website downloads the MSVC build so I assume that's what you should be using.

**Comment by yum13241** [comment]
So the only reason you bother to build MinGW is for completeness? Or is it because it's autobuilt?

**Comment by fn2006** [comment]
It's automatically built like all the other builds, Prism started including MSVC builds in addition to MinGW a little while ago.
I'm not sure why they started doing this but I assume it has something to do with the MSVC builds being half the size and only MSVC being built for ARM.

**Comment by TayouVR** [comment]
MinGW stopped supporting windows 7 and is a lot slower to build than MSVC, in addition MSVC allows us to build for x64, x86 (32bit) and arm64, MinGW doesn't support arm at all to my knowledge.
The reason we still have MinGW builds is because; well, they were already there and still work, but also; the MSVC builds need Microsoft Visual C++ Redsitributable (vcredist), which the MinGW builds don't need.
For most people that doesn't matter as they probably have that already anyways, but for e.g. a portable install on a USB stick you might prefer the MinGW build.

**Comment by fn2006** [comment]
Thank you for the explanation, I appreciate it.
