### ISSUE TITLE
Exclude installed mods from mod downloader.

### ISSUE THREAD

**Issue by ghost** [fn2006/PollyMC#7]
### Role

I make modpacks.

### Suggestion

I want already installed/selected mods to be excluded from the mod downloader.

### Benefit

So that installing mods that are available on both Modrinth and CurseForge doesn't turn into a nightmare.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm not sure if it's out of scope for PollyMC, if so, please do tell. But this alone would be the holy grail for me, and I imagine many modpack creators too.

Another thing that would be nice would be hiding/separating the mods already selected for download on a different list within the mod downloader window.

For example, when you selected Sodium for download on Modrinth, then find it on the CurseForge tab, it is already selected. I would like for Sodium to be hidden from both after selecting, and maybe moved to a "Mods Selected for Download" list within the mod downloader window.

---

**For context:** I've been building a modpack for personal use. Since CurseForge doesn't allow you to specifically search for 1.19+Fabric mods, I went to Modrinth. I scrolled through all 50+ pages of mods adding what I liked.
I gave up on CurseForge since going through every single mod page and clicking 3 times to see the "all files" page to finally found out if they're available for 1.19 or not is absolute madness.

Then, I found out about fibermc.com, which lists all mods for Fabric on both Modrinth and CurseForge, and allows you to actually filter them properly. However, it's not perfect, and I've already found mods that are available for Fabric 1.19, but are not listed there.

Either way, after realizing that a basic Minecraft launcher wouldn't do it for me anymore, I found PolyMC, then I found this, because fuck Microsoft.

And now that I know about the mod downloader I feel absolutely stupid for going through so much trouble when a readily available tool for my needs already existed.

---

So now, the only thing that's missing to make this launcher perfect is this feature. Although I'm making the modpack for personal use, I would like to export it.

With this feature, I would be able to go through all of Modrinth's mods (since after [this](https://blog.modrinth.com/modpack-changes/), I would rather not use CurseForge links), and only then go through CurseForge's list, without fear of "did I install this mod already?", and also making the list completely clean and extremely easier to navigate.

---

Unrelated, but it is actually hard to find this fork through Google alone. I could only find it by searching "Cracked PolyMC" and going through a reddit post. Searching "PollyMC" doesn't show anything. Maybe adding keywords like "Offline PolyMC" or again, "Cracked PolyMC" would help, although searching for those makes other similar forks appear. Either way, it's something I thought you should know.

**Comment by fn2006** [comment]
This seems like a really useful feature and it doesn't violate any EULAs, try opening an issue in the PolyMC repo, just don't mention this fork and they'll probably like it.
If they shoot it down for some reason I could try hacking something together but I'm not very experienced in C++ and this fork is the first time I've used Qt so the PolyMC devs would definitely do a better job than me.

On your other point about finding this fork, I'm going to rewrite the readme soon so that it explains what this fork is rather than just disclaiming that it's not endorsed by PolyMC which will probably improve SEO.

Also unrelated, it feels weird that this has almost 30 stars and people opening issues, it was originally just for personal use by me and a few friends until one of them posted a link to the repo on reddit.

**Comment by id404acc** [comment]
The OP actually did post this in the PolyMC repo, but it's down to page 3 already. Only one person commented on it, and considering the amount of issues/requests they have already, it's improbable it will be added.

So, if this interests you as well, I'd say go for it. 

However I do think it would be easier if you follow the mentioned comment's advice: simply mark the already downloaded mods instead of excluding them. maybe change the color of the background for that mod or something.

**Comment by fn2006** [comment]
I've done some thinking about this and decided I'm not going to implement this myself.
The mod downloader is one of the most worked on parts of PolyMC, adding this would cause more merge conflicts than it's worth, sorry.
